[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/zhimingkuang/Harvard-AM-115/blob/main/10_markov_chain/queuing_markov.ipynb)

In [1]:
import numpy as np

In [2]:
N = 10000 # number of trials
nt = 100 # number of time steps
p = 0.05
q = 0.08

In [3]:
state = np.ones(N)
for i in range(nt):
    probs = np.histogram(state, [1,2,3,4])[0] / N
    print('probability =',probs)
    for j in range(N):
        r = float(np.random.rand(1))
        if state[j] == 1:
            if r < p:
                state[j] = 2
        elif state[j]==2:
            if r < p:
                state[j] = 3
            elif r < p+q:
                state[j] = 1
        else:
            if r < q:
                state[j] = 2

probability = [1. 0. 0.]
probability = [0.9454 0.0546 0.    ]
probability = [0.9036 0.0937 0.0027]
probability = [0.8688 0.1235 0.0077]
probability = [0.8322 0.1572 0.0106]
probability = [0.8031 0.1791 0.0178]
probability = [0.7769 0.1987 0.0244]
probability = [0.7529 0.2148 0.0323]
probability = [0.7326 0.2285 0.0389]
probability = [0.712  0.2396 0.0484]
probability = [0.6983 0.2454 0.0563]
probability = [0.6814 0.254  0.0646]
probability = [0.6642 0.2631 0.0727]
probability = [0.6535 0.2673 0.0792]
probability = [0.6388 0.2748 0.0864]
probability = [0.6311 0.2768 0.0921]
probability = [0.6221 0.278  0.0999]
probability = [0.616  0.2769 0.1071]
probability = [0.6063 0.2802 0.1135]
probability = [0.5975 0.2842 0.1183]
probability = [0.59   0.2848 0.1252]
probability = [0.5829 0.2892 0.1279]
probability = [0.5775 0.29   0.1325]
probability = [0.5731 0.2879 0.139 ]
probability = [0.5699 0.2897 0.1404]
probability = [0.5642 0.2932 0.1426]
probability = [0.5604 0.2954 0.1442]
probability =

In [4]:
A = np.array([[1-p,q,0],[p,1-p-q, q],[0,p,1-q]])
[d,v] = np.linalg.eig(A)
print("A = \n", A)
print("Eigenvalues:\n", d)
print("Eigenvectors:\n", v) # note: eigenvectors have different value than MATLAB but
                            # they are linearly equivalent (A & eigenvalues are the same)

A = 
 [[0.95 0.08 0.  ]
 [0.05 0.87 0.08]
 [0.   0.05 0.92]]
Eigenvalues:
 [0.80675445 1.         0.93324555]
Eigenvectors:
 [[-0.45496212 -0.80498369 -0.77408722]
 [ 0.81464126 -0.5031148   0.16211754]
 [-0.35967914 -0.31444675  0.61196968]]
